### ISSUE TITLE
Pagination buttons are floating on the page when we scroll down

### ISSUE THREAD

**Issue by yoannsculo** [yoannsculo/JobCatcher#26]
![bug_pagination](https://f.cloud.github.com/assets/691328/1552998/b138afca-4e2c-11e3-8444-787378e4c7f8.png)

**Comment by yscialom** [comment]
There should be no scrolling: with the right number of offer per page (see config.py) the whole table fit in any screen. Though, we could let the upper panel of the report (links to reports and stats and the pagination navbar) in a fixed position and limit the scrolling to the table:

``` html
<p id="bobafett">
   <!-- upper panel -->
</p>
<p id="jarjarbinks">
   <table><!-- ... --></table>
</p>
```

``` css
#bobafett {
   display: block;
   position: fixed;
   height: 10em;
}
#jarjarbinks{
   display: block;
   position: absolute;
   top: 10em;
   height: ???
   overflow: auto;
}
```

The main trouble will come from the height of Jar Jar Binks
